# measure moments targets
# this if for targets
#srun --nodes=10 --tasks-per-node=16 --cpus-per-task=4 --cpu-bind=cores --mem=110GB python run_pipeline1.py
#this is for cpp
#srun --nodes=20 --tasks-per-node=4 --cpus-per-task=16 --cpu-bind=cores --mem=110GB python run_pipeline1.py

#srun --nodes=5 --tasks-per-node=5 --cpus-per-task=12 --cpu-bind=cores --mem=110GB python run_pipeline.py
#srun --nodes=5 --tasks-per-node=2 --cpus-per-task=30 --cpu-bind=cores --mem=110GB python run_pipeline.py
#srun --nodes=5 --tasks-per-node=5 --cpus-per-task=12 --cpu-bind=cores --mem=110GB python run_pipeline.py
## make targets - whatever is OK, no cost basically.
#srun --nodes= 20 --tasks-per-node=1 --cpus-per-task=60 --cpu-bind=cores --mem=110GB python run_pipeline.py
#measure moments deep field
#srun --nodes=20 --tasks-per-node=10 --cpus-per-task=6 --cpu-bind=cores --mem=110GB python run_pipeline.py
#make templates
#srun --nodes=20 --tasks-per-node=10 --cpus-per-task=6 --cpu-bind=cores --mem=110GB python run_pipeline.py
#srun --nodes=10 --tasks-per-node=2 --cpus-per-task=30 --cpu-bind=cores --mem=110GB python run_pipeline_

#srun --nodes=1 --tasks-per-node=1 --cpus-per-task=60 --cpu-bind=cores --mem=110GB python run_pipeline1.py
#srun --nodes=1 --tasks-per-node=16 --cpus-per-task=4 --cpu-bind=cores --mem=110GB python run_pipeline1.py




run:
     #- setup_image_sims
     - make_tiles_tt
     #- measure_moments_targets
     #- make_targets
     ##- measure_moments_templates
     #- make_templates
     #- cpp_part
#
######################################################################
#                       general config
######################################################################





general:
    output_folder: '/global/cscratch1/sd/mgatti/BFD/runs_collab_meeting/tile_highsn_grid_10k_manytargets_nobig_turbPSF_1.1_1.5PSF_benchmark/'
    n: 4.     # Default: 
    sigma: 0.55  # Default: 0.5
    band_dict: [['r',1.0]] # [['r',0.7],['i',0.2],['z',0.1]] #[['r',1.0]] #
    bands: ['r'] #['i', 'r', 'z'] #['r'] #
    MPI: True
######################################################################
#                       setup_image_sims
######################################################################

setup_image_sims:
    bands: ['r','i','z']
    stage: 'save_galaxy_params'
    MOF_table_path: '/global/project/projectdirs/des/BFD_Y6/deep_fields_coadd/mof/run-ugriz-mof02_marco.fits'
        
        
######################################################################
#                       make_tiles_tt
######################################################################

## MODE STAMP *****+
#grid input  -> all 0s, you get a 1 sometimes if you get a NaN
#grid detection -> all 0s, you get a 1 sometimes if you get a NaN and 1 if where there should be an input galaxy, there is nothing (ADD THIS) 
#
## MODE STAMP *****+
#random input no poisson -> all 0s, you get a 1 sometimes if you get a NaN
#random input poisson -> all 0s, you get a 1 sometimes if you get a NaN
#random detection  no poisson -> all 0s, you get a 1 sometimes if you get a NaN and add 1 if there's nothing
#random detection  poisson -> this is the real detection case.

make_tiles_tt:    
    do: ['templates'] #['targets','templates']
    size_tile: 500
    gal_per_tile: 20 # 40 is 12 gal /arcmin^2, 100 is 32       40./(420*420*0.25*0.25/3600.)
    number_of_replicas: 10 ##1600 #3200 #400
    n_targets: 20 #12800 #38400
    n_templates: 10000
    models: '/project/projectdirs/des/BFD_Y6/bfd/Marco/chunk_10k_similarSN_deep_fields_bdf_models_wphotoz_PSF_fixed.npy'
    #models: '/project/projectdirs/des/BFD_Y6/bfd/Marco//chunk_10k_similarSN_deep_fields_bdf_models_wphotoz_PSF_fixed.npy'
    noise_ext: [2.3,2.5]
    noise_factor: 0.02
    noise_ext_templates: [0.002]
    grid_targets: False
    grid_templates: False
    poisson: False
    mode_detection: 'detection' #'detection' #'input'
    index_P0_PSF: 'turb'
    index_P0: False
    noiseless: False
    maskless: True
    resize_sn: 1.
    pad_factor: 3.
    radius_blends_templates: 2. #arcsec.
    size_treshold: 1.
    g1: [0.02,-0.02]
    g2: [0.,0.]
        
######################################################################
#                       measure_moments_targets
######################################################################

measure_moments_targets:
    # This first part parallelises (MPI) on tiles and it does 5x multiprocessing on chunk size.
    # Usually 1 tile per node is enough.

    path_data: '/global/cscratch1/sd/mgatti/BFD/data/'
    tiles: ['DES2347-5414'] # It can be 'ALL', a random number of tiles (e.g., 20), or a list with the names of the tiles.
    agents_chunk: 10
    chunk_size: 200 #200. # It measures the moments CHUNK_SIZE targets simulataneously
    max_target_per_tile: 10000 # 00 #00 # 40000
    MOF_subtraction: False
    shredder: None #path for the MOF subtraction
    cut_psf : [False,25]
    MPI_per_tile : True # speed up for testing on 1 TILE
    minimum_number_of_bands : 1
    interp_masking : False
    frac_limit: 0.3 # limit for throwing away targets
    COADD_only: True

    # simulate targets ******************************
    simulated_templates: '/project/projectdirs/des/BFD_Y6/bfd/Marco/chunk_5k_similarSN_deep_fields_bdf_models_wphotoz_PSF_fixed_mag22.npy'
    setup_image_sims: True
    noise_factor: 1.9 # 0.03 #. 0.06 #0.1 and index_P0,index_P0_PSF=40 for basic high SNR run.
    noise_ext: [1.,1.3]
    number_of_replicas: 1  #50 #300 # it generates 5x simulated targets from each stamp.
    g1: [0.02,-0.02]
    g2: [0.,0.]
    maskless: True
    noiseless: False
    #fix the galaxy & PSFfor all. I've set it to 40 in the past.
    index_P0: 40
    index_P0_PSF: 40
    index_fixed: 500    
    
######################################################################
#                       make_target
######################################################################

make_targets:
    # we divide the targets into bins depending on the covariance of Mf.
    # to compare with cov_mf take the power of two
    #sigmaM_min: 4.632   #   150
    #sigmaM_max: 7.8 # 15000
    # additional cuts:
    sn_min: 20    # minimum S/N on flux
    sn_max: 5000
    Mf_max: 90000
    Mf_min: 0.

######################################################################
#                       measure_moments_templates
######################################################################

measure_moments_templates:
    # There are ~ 244 tiles in des y3 deep fields. it's all parallelised with MPI, running on each tile.
    # srun --nodes= 10 --tasks-per-node=10 --cpus-per-task=6 --cpu-bind=cores --mem=110GB python run_pipeline.py


    path_coadd_deepfields: '/global/project/projectdirs/des/BFD_Y6/deep_fields_coadd/'
    deep_fields_catalog: '/global/project/projectdirs/des/BFD_Y6/deep_fields_coadd/y3_deep_fields.fits'
    fields: ['COSMOS_UltraVISTA_Willv2'] # , 'SN-C3', 'SN-E2', 'SN-X3']
    tiles: ['COSMOS_C32_r3764p01']
    agents_chunk: 6
    chunk_size: 100
    max_target_per_tile: 5000 # 00
    MOF_subtraction: False
    shredder: '/global/project/projectdirs/des/BFD_Y6/deep_fields_coadd/mof/run-ugriz-mof02.fits'
    cut_psf : [False,25]
    minimum_number_of_bands : 1 # set it to the max otherwise bias incoming! -- 
    interp_masking : False
    frac_limit: 0.3 # limit for throwing away targets
    COADD_only: True

    # image simlations setup ******
    simulated_templates: '/project/projectdirs/des/BFD_Y6/bfd/Marco/chunk_5k_similarSN_deep_fields_bdf_models_wphotoz_PSF_fixed_mag22.npy'
    setup_image_sims: True
    number_of_replicas: 20 #do not change for templates
    noise_factor: 0.01
    noise_ext: False
    maskless: True
    noiseless: False
    index_P0: False
    index_P0_PSF: 40
    index_fixed: 500 # you can't use it with multiple templates --
######################################################################
#                       make_templates
######################################################################

make_templates:
    sigma_max: 6.5 # we only keep templates within sigma_max (chi2 includes MX,MY,Mf,det supression)
    sigma_step: 1.2 #maximum shift between template
    xy_max: 2         
    sn_min: 0 # minimum S/N on flux
    chunks: 5 # It makes templates from #obj tile /chunks deep fields galaxies at a time
    sn_max: 50000000000 # properties of the templates!!
    Mf_max: 900000 # properties of the templates!!
    Mf_min: 0.    # properties of the templates!!
    stage: ['compute','assembly'] #['compute','assembly']
    #stage: ['assembly'] #['compute','assembly']
    
    

                                
###############
cpp_part:
    chunks: 80
    image_sims: True
    noise_tiers: [1,2,3,4,5]
    minsn: 5. #10
    maxsn: 200 #20
    number_targets_chunk: 12000
    add_labels: ['ISp_','ISm_'] #,'ISm_']
    #noise_tiers: [5]
    stage: ['assemble','compute_m'] #,'assemble','compute_m'] #['split','integrate','assemble','selection']
    
    #stage: ['assemble','compute_m'] #,'compute_m'] #['split','integrate','assemble','selection']
    #stage: ['integrate'] #,'compute_m']
    #stage: ['integrate'] #,'assemble','compute_m'] #,'assemble','selection','compute_m'] #['split','integrate','assemble','selection']
   
   # stage: ['integrate'] #,'assemble','selection','compute_m'] #['split','integrate','assemble','selection']
    #stage: ['assemble','compute_m'] #,'assemble','selection','compute_m'] #['split','integrate','assemble','selection']
    #stage: ['split','integrate'] #,'assemble','compute_m'] 
   # stage: ['selection','assemble'] #,'assemble','compute_m'] #,'integrate','assemble','selection','compute_m'] #,'integrate'] #
    #stage: ['selection','compute_m'] #,'selection','compute_m'] #,'integrate'] #['split','integrate','assemble']
    
    
# /global/project/projectdirs/des/BFD_Y6/bfd/bin/meanShear -targetFile=/global/cscratch1/sd/mgatti/BFD/runs_collab_meeting/more_realistic_varynoise2_varying_PSF_lowSN_selection/ISp_targets_sample_g.fits -stampSelection=T

#-stampSelection=F 
# 1b: -0.00096 +- 0.00035
# 1b 25psf: -0.00286 +- 0.00035
# 3b = -0.00060 +- 0.00040
# 3b 25 psf = 0.00173 +- 0.00047