#srun --nodes=1 --tasks-per-node=128 --cpus-per-task=2 --cpu-bind=cores python ./run_bfd.py --config ../BFD_pipeline_vwetzell/config/config_data.yaml --tiles DES0137-3749 --output_label _run1

run:
     - measure_moments_targets

######################################################################
#                       general config
######################################################################

general:
    output_folder:  '/pscratch/sd/m/mgatti/BFD/_test_bfd_y6kp/'
    
    # BFD window function parameters. Defaults: n = 4, sigma = 0.65
    filter_sigma: 0.65  
    
    # per-band weights.
    bands_meds_files: ['g','r','i','z']
    bands_weights: [0.,0.7,0.2,0.1]

    # pad factor for the FFT of the images. Default: 2. 
    FFT_pad_factor: 2.
    
    # whether if you want to use MPI or not.
    MPI: False

        
######################################################################
#                       measure_moments_targets
######################################################################

measure_moments_targets:

    path_MEDS: '/pscratch/sd/m/mgatti/BFD/data/'
    path_galaxy_models: '/pscratch/sd/m/mgatti/BFD/models/'
    tiles: ['DES0009-6248']
    exp_list: '/global/homes/m/mgatti/BFD_pipeline/data/PSF_cuts.npy'
    debug: True
    max_frac_stamp_masked: 0.05
    
