#srun --nodes=1 --tasks-per-node=60 --cpus-per-task=1 --cpu-bind=cores python ./run_bfd.py --config config/config_data.yaml --tiles DES0137-3749 --output_label _run1

run:
     - measure_moments_targets
    
     
     
##
######################################################################
#                       general config
######################################################################


general:
    output_folder: '/pscratch/sd/m/mgatti/BFD//_test1'
    n: 4.     # Default: 
    sigma: 0.55  # Default: 0.5
    band_dict: [['r',0.7],['i',0.2],['z',0.1]] #[['r',1.0]] #
    bands: ['r', 'i', 'z'] #['r'] #
    MPI: False
    pad_factor: 4.
  
        
######################################################################
#                       measure_moments_targets
######################################################################

measure_moments_targets:

    path_data: '/pscratch/sd/m/mgatti/BFD/data/'
    output_label: ''
    tiles: ['DES0137-3749'] 
    agents_chunk: 20  # works if MPI_per_tile is False. Spawns X multiprocess
    chunk_size: 1500 
    max_target_per_tile: 100000 
    MOF_subtraction: True
    shredder: True
    path_shredder: '/pscratch/sd/m/mgatti/BFD/data/shredx/'
    cut_psf : [False,25]
    MPI_per_tile : True # speed up for testing on 1 TILE
    minimum_number_of_bands : 3
    interp_masking : False
    subtract_background : False
    add_detection_stamp : False
    frac_limit: 0.3 # limit for throwing away targets
    COADD_only: False
    run_mcal: False
    debug: False
    setup_image_sims: False  
    
