#srun --nodes=4 --tasks-per-node=1  python ./run_bfd.py --config ./config/config_measure_template_moments_only.yaml 
run:
     - measure_moments_templates
   # - make_templates
######################################################################
#                       general config
######################################################################

general:
    output_folder:  '/pscratch/sd/m/mgatti/BFD/_test_bfd_y6kp_0.65_fiducial/'
    
    # BFD window function parameters. Defaults: n = 4, sigma = 0.65
    filter_sigma: 0.65 #65  
    
    # per-band weights.
    bands_meds_files: ['g','r','i','z']
    bands_weights: [0.,0.6,0.3,0.1]

    # pad factor for the FFT of the images. Default: 2. 
    FFT_pad_factor: 2.
    
    # whether if you want to use MPI or not.
    MPI: True

        
######################################################################
#                       measure_moments_targets
######################################################################

measure_moments_templates:

    max_frac_stamp_masked: 0.05
    path_MEDS: '/global/cfs/cdirs/des/BFD_Y6/deep_fields_coadd_PIFF/'
    desy3_DF: '/global/cfs/cdirs/des/BFD_Y6/deep_fields_coadd/deep_fields_y3kp2.h5'
    path_galaxy_models: '/pscratch/sd/m/mgatti/BFD/data/fitdv_df_collated_2/'
   # path_galaxy_models: '/pscratch/sd/m/mgatti/BFD/data/fitdv_ref/'
    debug: False
    debug_SN : False
    compute_shotnoise_fluxes: False # computes the shotnoise contribution to the fluxes for the high SN templates.
    #fields: ['COSMOS_UltraVISTA_Willv2']
    #tiles:  ['COSMOS_C27_r3764p01'] 


    fields: ['COSMOS_UltraVISTA_Willv2','SN-E2','SN-X3','SN-C3'] 
    tiles: 'All' 
            
   
   
######################################################################
#                      make templates
######################################################################
make_templates:
    sigma_max: 5.5 # we only keep templates within sigma_max (chi2 includes MX,MY,Mf,det supression)
    sigma_step: 1.2 #maximum shift between template
    xy_max: 2         
    sn_min: 7
    