#srun --nodes=1 --tasks-per-node=128 --cpus-per-task=2 --cpu-bind=cores python ./run_bfd.py --config ../BFD_pipeline_vwetzell/config/config_data.yaml --tiles DES0137-3749 --output_label _run1

run:
     - measure_moments_targets

######################################################################
#                       general config
######################################################################

general:
    output_folder:  '/global/cscratch1/sd/mgatti/BFD//_test_new_mask005_V/'
    
    # BFD window function parameters. Defaults: n = 4, sigma = 0.65
    filter_sigma: 0.65  
    
    # per-band weights.
    bands_meds_files: ['g','r','i','z']
    bands_weights: [0.,0.7,0.2,0.1]

    # pad factor for the FFT of the images. Default: 2. 
    FFT_pad_factor: 2.
    
    # whether if you want to use MPI or not.
    MPI: False

        
######################################################################
#                       measure_moments_targets
######################################################################

measure_moments_targets:

    path_MEDS: '/pscratch/sd/m/mgatti/BFD/data/'
    path_galaxy_models: '/pscratch/sd/m/mgatti/BFD/models/'
    tiles: ['DES0009-6248']
    flagged_exp_list: '/global/homes/m/mgatti/BFD_pipeline/data/PSF_cuts.npy'
    max_frac_stamp_masked: 0.1
    

    output_label: ''
    tiles: ['DES0137-3749'] 
    agents_chunk: 20  # works if MPI_per_tile is False. Spawns X multiprocess
    chunk_size: 1500 
    max_target_per_tile: 100000 
    MOF_subtraction: True
    shredder: True
    filter:  'KBlackmanHarris' #'normal'
    path_shredder: '/global/cscratch1/sd/mgatti/BFD//data_y6/shredex/'
    

    
    interp_masking : True
    subtract_background : True
    add_detection_stamp : False
    frac_limit: 0.1 # limit for throwing away targets
    COADD_only: False
    run_mcal: False
    debug: False
    setup_image_sims: False  
    SN_limit_tosavetemplates: 80
    exp_list: '/global/homes/m/mgatti/BFD_pipeline/data/PSF_cuts.npy'
    
    
