#srun --nodes=1 --tasks-per-node=60 --cpus-per-task=1 --cpu-bind=cores python ./run_bfd.py --config config/config_data.yaml --tiles DES0137-3749 --output_label _run1
#srun --nodes=4 --tasks-per-node=2 --cpus-per-task=32 --cpu-bind=cores python ./run_bfd.py --config config/config_data.yaml
#srun --nodes=1 --tasks-per-node=1 --cpus-per-task=32 --cpu-bind=cores python ./run_bfd.py --config config/config_data.yaml
run:
     - measure_moments_targets
     #- make_targets
     #- cpp_part
     
##
######################################################################
#                       general config
######################################################################


general:
    #output_folder:  '/pscratch/sd/m/mgatti/BFD/_test_80_SN/'  #'/global/cscratch1/sd/mgatti/BFD//_test_ref_bck/'
    output_folder:  '/pscratch/sd/v/vwetzell/BFD/tile_DES0137-3749_KBH_090/'  #'/global/cscratch1/sd/mgatti/BFD//_test_ref_bck/'
    n: 4.     # Default: 
    sigma: 0.495 
    band_dict: [['g',0.],['r',0.7],['i',0.2],['z',0.1]] #[['r',1.0]] #
    bands: ['g','r', 'i', 'z'] #['r'] #
    MPI: False
    pad_factor: 4.
  
        
######################################################################
#                       measure_moments_targets
######################################################################

measure_moments_targets:

    path_data: '/pscratch/sd/v/vwetzell/BFD/data/'
    output_label: ''
    tiles: ['DES0137-3749'] 
    agents_chunk: 200  # works if MPI_per_tile is False. Spawns X multiprocess
    chunk_size: 350 
    max_target_per_tile: 100000 
    MOF_subtraction: True
    shredder: True
    path_shredder: '/pscratch/sd/v/vwetzell/BFD/data/shredex/'
    cut_psf : [False,25]
    MPI_per_tile : False # speed up for testing on 1 TILE
    minimum_number_of_bands : ['r', 'i', 'z']
    interp_masking : True
    subtract_background : True
    add_detection_stamp : False
    frac_limit: 0.1 # limit for throwing away targets
    COADD_only: False
    run_mcal: False
    debug: False
    setup_image_sims: False  
    
    
######################################################################
#                      make_targets
######################################################################

make_targets:
    # we divide the targets into bins depending on the covariance of Mf.
    # to compare with cov_mf take the power of two
    #sigmaM_min: 4.632   #   150
    #sigmaM_max: 7.8 # 15000
    # additional cuts:
    sn_min: 7.
    sn_max: 80.
    Mf_max: 90000
    Mf_min: 0.
    re_run_noisetiers: False
    noiseStep: 0.35
    psfStep: 0.25
    match_to_gold: '/global/cfs/cdirs/des/BFD_Y6/gold_id.npy'
    
    
    
    
                                
######################################################################
#                       bayesian integration
######################################################################

cpp_part:
    bacth_size_templates: 2000000
    bacth_size_targets: 10000000
    option: noisetiers_chunks 
    add_labels: [''] 
    path_cpp: '/pscratch/sd/v/vwetzell/bfd_vwetzell/bin/'
    #stage: ['selection','selection_ave'] 
    #stage: ['assemble'] #,'integrate','assemble']
    stage: ['assemble'] #,'assemble']
    #